
environments:
  dev:
  prod:

repositories:
- name: yesodot
  url: https://harborreg-2.northeurope.cloudapp.azure.com/chartrepo/library
  username: { requiredEnv "HARBOR_USER" }
  password: { requiredEnv "HARBOR_PASSWORD" }

releases:
- name: client-example
  namespace: abc
  chart: yesodot/common
  version: { requiredEnv "COMMON_VERSION" | default "0.5.2" }
  values:
    - ../{ .Environment.Name }-values/client-example.yaml
  installed: true 
- name: authenticator-example
  namespace: abc
  chart: yesodot/common
  version: { requiredEnv "COMMON_VERSION" | default "0.5.2" }
  values:
    - ../{ .Environment.Name }-values/authenticator-example.yaml
  installed: true 
- name: api-example
  namespace: abc
  chart: yesodot/common
  version: { requiredEnv "COMMON_VERSION" | default "0.5.2" }
  values:
    - ../{ .Environment.Name }-values/api-example.yaml
  installed: true 